apiVersion: v2
name: order-environment
description: Umbrella Helm chart for order-service environment
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: order-service
    version: "0.9.0"
    repository: "oci://684120555936.dkr.ecr.ap-south-1.amazonaws.com"